// <auto-generated>
/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.128
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Represents the data for the context annotation domain.
    /// </summary>
    public partial class ContextAnnotationDomainFields : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContextAnnotationDomainFields" /> class.
        /// </summary>
        /// <param name="id">The unique id for a context annotation domain.</param>
        /// <param name="description">Description of the context annotation domain.</param>
        /// <param name="name">Name of the context annotation domain.</param>
        [JsonConstructor]
        public ContextAnnotationDomainFields(string id, Option<string?> description = default, Option<string?> name = default)
        {
            Id = id;
            DescriptionOption = description;
            NameOption = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The unique id for a context annotation domain.
        /// </summary>
        /// <value>The unique id for a context annotation domain.</value>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Description of the context annotation domain.
        /// </summary>
        /// <value>Description of the context annotation domain.</value>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Name of the context annotation domain.
        /// </summary>
        /// <value>Name of the context annotation domain.</value>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ContextAnnotationDomainFields {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.Id != null) {
                // Id (string) pattern
                Regex regexId = new Regex(@"^[0-9]{1,19}$", RegexOptions.CultureInvariant);

                if (!regexId.Match(this.Id).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Id, must match a pattern of " + regexId, new [] { "Id" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ContextAnnotationDomainFields" />
    /// </summary>
    public class ContextAnnotationDomainFieldsJsonConverter : JsonConverter<ContextAnnotationDomainFields>
    {
        /// <summary>
        /// Deserializes json to <see cref="ContextAnnotationDomainFields" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ContextAnnotationDomainFields Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> description = default;
            Option<string?> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ContextAnnotationDomainFields.", nameof(id));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ContextAnnotationDomainFields.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class ContextAnnotationDomainFields.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ContextAnnotationDomainFields.");

            return new ContextAnnotationDomainFields(id.Value!, description, name);
        }

        /// <summary>
        /// Serializes a <see cref="ContextAnnotationDomainFields" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="contextAnnotationDomainFields"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ContextAnnotationDomainFields contextAnnotationDomainFields, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, contextAnnotationDomainFields, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ContextAnnotationDomainFields" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="contextAnnotationDomainFields"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ContextAnnotationDomainFields contextAnnotationDomainFields, JsonSerializerOptions jsonSerializerOptions)
        {
            if (contextAnnotationDomainFields.Id == null)
                throw new ArgumentNullException(nameof(contextAnnotationDomainFields.Id), "Property is required for class ContextAnnotationDomainFields.");

            if (contextAnnotationDomainFields.DescriptionOption.IsSet && contextAnnotationDomainFields.Description == null)
                throw new ArgumentNullException(nameof(contextAnnotationDomainFields.Description), "Property is required for class ContextAnnotationDomainFields.");

            if (contextAnnotationDomainFields.NameOption.IsSet && contextAnnotationDomainFields.Name == null)
                throw new ArgumentNullException(nameof(contextAnnotationDomainFields.Name), "Property is required for class ContextAnnotationDomainFields.");

            writer.WriteString("id", contextAnnotationDomainFields.Id);

            if (contextAnnotationDomainFields.DescriptionOption.IsSet)
                writer.WriteString("description", contextAnnotationDomainFields.Description);

            if (contextAnnotationDomainFields.NameOption.IsSet)
                writer.WriteString("name", contextAnnotationDomainFields.Name);
        }
    }
}
