// <auto-generated>
/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.128
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DmMediaAttachment
    /// </summary>
    public partial class DmMediaAttachment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DmMediaAttachment" /> class.
        /// </summary>
        /// <param name="mediaId">The unique identifier of this Media.</param>
        [JsonConstructor]
        public DmMediaAttachment(string mediaId)
        {
            MediaId = mediaId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The unique identifier of this Media.
        /// </summary>
        /// <value>The unique identifier of this Media.</value>
        /* <example>1146654567674912769</example> */
        [JsonPropertyName("media_id")]
        public string MediaId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DmMediaAttachment {\n");
            sb.Append("  MediaId: ").Append(MediaId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.MediaId != null) {
                // MediaId (string) pattern
                Regex regexMediaId = new Regex(@"^[0-9]{1,19}$", RegexOptions.CultureInvariant);

                if (!regexMediaId.Match(this.MediaId).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MediaId, must match a pattern of " + regexMediaId, new [] { "MediaId" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DmMediaAttachment" />
    /// </summary>
    public class DmMediaAttachmentJsonConverter : JsonConverter<DmMediaAttachment>
    {
        /// <summary>
        /// Deserializes json to <see cref="DmMediaAttachment" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DmMediaAttachment Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> mediaId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "media_id":
                            mediaId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!mediaId.IsSet)
                throw new ArgumentException("Property is required for class DmMediaAttachment.", nameof(mediaId));

            if (mediaId.IsSet && mediaId.Value == null)
                throw new ArgumentNullException(nameof(mediaId), "Property is not nullable for class DmMediaAttachment.");

            return new DmMediaAttachment(mediaId.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="DmMediaAttachment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dmMediaAttachment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DmMediaAttachment dmMediaAttachment, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dmMediaAttachment, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DmMediaAttachment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dmMediaAttachment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DmMediaAttachment dmMediaAttachment, JsonSerializerOptions jsonSerializerOptions)
        {
            if (dmMediaAttachment.MediaId == null)
                throw new ArgumentNullException(nameof(dmMediaAttachment.MediaId), "Property is required for class DmMediaAttachment.");

            writer.WriteString("media_id", dmMediaAttachment.MediaId);
        }
    }
}
