// <auto-generated>
/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.128
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// User compliance data.
    /// </summary>
    public partial class UserComplianceData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserComplianceData" /> class.
        /// </summary>
        /// <param name="userProtectComplianceSchema"></param>
        public UserComplianceData(UserProtectComplianceSchema userProtectComplianceSchema)
        {
            UserProtectComplianceSchema = userProtectComplianceSchema;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserComplianceData" /> class.
        /// </summary>
        /// <param name="userUnprotectComplianceSchema"></param>
        public UserComplianceData(UserUnprotectComplianceSchema userUnprotectComplianceSchema)
        {
            UserUnprotectComplianceSchema = userUnprotectComplianceSchema;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserComplianceData" /> class.
        /// </summary>
        /// <param name="userDeleteComplianceSchema"></param>
        public UserComplianceData(UserDeleteComplianceSchema userDeleteComplianceSchema)
        {
            UserDeleteComplianceSchema = userDeleteComplianceSchema;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserComplianceData" /> class.
        /// </summary>
        /// <param name="userUndeleteComplianceSchema"></param>
        public UserComplianceData(UserUndeleteComplianceSchema userUndeleteComplianceSchema)
        {
            UserUndeleteComplianceSchema = userUndeleteComplianceSchema;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserComplianceData" /> class.
        /// </summary>
        /// <param name="userSuspendComplianceSchema"></param>
        public UserComplianceData(UserSuspendComplianceSchema userSuspendComplianceSchema)
        {
            UserSuspendComplianceSchema = userSuspendComplianceSchema;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserComplianceData" /> class.
        /// </summary>
        /// <param name="userUnsuspendComplianceSchema"></param>
        public UserComplianceData(UserUnsuspendComplianceSchema userUnsuspendComplianceSchema)
        {
            UserUnsuspendComplianceSchema = userUnsuspendComplianceSchema;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserComplianceData" /> class.
        /// </summary>
        /// <param name="userWithheldComplianceSchema"></param>
        public UserComplianceData(UserWithheldComplianceSchema userWithheldComplianceSchema)
        {
            UserWithheldComplianceSchema = userWithheldComplianceSchema;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserComplianceData" /> class.
        /// </summary>
        /// <param name="userScrubGeoSchema"></param>
        public UserComplianceData(UserScrubGeoSchema userScrubGeoSchema)
        {
            UserScrubGeoSchema = userScrubGeoSchema;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserComplianceData" /> class.
        /// </summary>
        /// <param name="userProfileModificationComplianceSchema"></param>
        public UserComplianceData(UserProfileModificationComplianceSchema userProfileModificationComplianceSchema)
        {
            UserProfileModificationComplianceSchema = userProfileModificationComplianceSchema;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets UserProtectComplianceSchema
        /// </summary>
        public UserProtectComplianceSchema? UserProtectComplianceSchema { get; set; }

        /// <summary>
        /// Gets or Sets UserUnprotectComplianceSchema
        /// </summary>
        public UserUnprotectComplianceSchema? UserUnprotectComplianceSchema { get; set; }

        /// <summary>
        /// Gets or Sets UserDeleteComplianceSchema
        /// </summary>
        public UserDeleteComplianceSchema? UserDeleteComplianceSchema { get; set; }

        /// <summary>
        /// Gets or Sets UserUndeleteComplianceSchema
        /// </summary>
        public UserUndeleteComplianceSchema? UserUndeleteComplianceSchema { get; set; }

        /// <summary>
        /// Gets or Sets UserSuspendComplianceSchema
        /// </summary>
        public UserSuspendComplianceSchema? UserSuspendComplianceSchema { get; set; }

        /// <summary>
        /// Gets or Sets UserUnsuspendComplianceSchema
        /// </summary>
        public UserUnsuspendComplianceSchema? UserUnsuspendComplianceSchema { get; set; }

        /// <summary>
        /// Gets or Sets UserWithheldComplianceSchema
        /// </summary>
        public UserWithheldComplianceSchema? UserWithheldComplianceSchema { get; set; }

        /// <summary>
        /// Gets or Sets UserScrubGeoSchema
        /// </summary>
        public UserScrubGeoSchema? UserScrubGeoSchema { get; set; }

        /// <summary>
        /// Gets or Sets UserProfileModificationComplianceSchema
        /// </summary>
        public UserProfileModificationComplianceSchema? UserProfileModificationComplianceSchema { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserComplianceData {\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UserComplianceData" />
    /// </summary>
    public class UserComplianceDataJsonConverter : JsonConverter<UserComplianceData>
    {
        /// <summary>
        /// Deserializes json to <see cref="UserComplianceData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UserComplianceData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            UserProtectComplianceSchema? userProtectComplianceSchema = default;
            UserUnprotectComplianceSchema? userUnprotectComplianceSchema = default;
            UserDeleteComplianceSchema? userDeleteComplianceSchema = default;
            UserUndeleteComplianceSchema? userUndeleteComplianceSchema = default;
            UserSuspendComplianceSchema? userSuspendComplianceSchema = default;
            UserUnsuspendComplianceSchema? userUnsuspendComplianceSchema = default;
            UserWithheldComplianceSchema? userWithheldComplianceSchema = default;
            UserScrubGeoSchema? userScrubGeoSchema = default;
            UserProfileModificationComplianceSchema? userProfileModificationComplianceSchema = default;

            Utf8JsonReader utf8JsonReaderOneOf = utf8JsonReader;
            while (utf8JsonReaderOneOf.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (utf8JsonReaderOneOf.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderOneOf.CurrentDepth - 1)
                {
                    Utf8JsonReader utf8JsonReaderUserProtectComplianceSchema = utf8JsonReader;
                    ClientUtils.TryDeserialize<UserProtectComplianceSchema?>(ref utf8JsonReaderUserProtectComplianceSchema, jsonSerializerOptions, out userProtectComplianceSchema);

                    Utf8JsonReader utf8JsonReaderUserUnprotectComplianceSchema = utf8JsonReader;
                    ClientUtils.TryDeserialize<UserUnprotectComplianceSchema?>(ref utf8JsonReaderUserUnprotectComplianceSchema, jsonSerializerOptions, out userUnprotectComplianceSchema);

                    Utf8JsonReader utf8JsonReaderUserDeleteComplianceSchema = utf8JsonReader;
                    ClientUtils.TryDeserialize<UserDeleteComplianceSchema?>(ref utf8JsonReaderUserDeleteComplianceSchema, jsonSerializerOptions, out userDeleteComplianceSchema);

                    Utf8JsonReader utf8JsonReaderUserUndeleteComplianceSchema = utf8JsonReader;
                    ClientUtils.TryDeserialize<UserUndeleteComplianceSchema?>(ref utf8JsonReaderUserUndeleteComplianceSchema, jsonSerializerOptions, out userUndeleteComplianceSchema);

                    Utf8JsonReader utf8JsonReaderUserSuspendComplianceSchema = utf8JsonReader;
                    ClientUtils.TryDeserialize<UserSuspendComplianceSchema?>(ref utf8JsonReaderUserSuspendComplianceSchema, jsonSerializerOptions, out userSuspendComplianceSchema);

                    Utf8JsonReader utf8JsonReaderUserUnsuspendComplianceSchema = utf8JsonReader;
                    ClientUtils.TryDeserialize<UserUnsuspendComplianceSchema?>(ref utf8JsonReaderUserUnsuspendComplianceSchema, jsonSerializerOptions, out userUnsuspendComplianceSchema);

                    Utf8JsonReader utf8JsonReaderUserWithheldComplianceSchema = utf8JsonReader;
                    ClientUtils.TryDeserialize<UserWithheldComplianceSchema?>(ref utf8JsonReaderUserWithheldComplianceSchema, jsonSerializerOptions, out userWithheldComplianceSchema);

                    Utf8JsonReader utf8JsonReaderUserScrubGeoSchema = utf8JsonReader;
                    ClientUtils.TryDeserialize<UserScrubGeoSchema?>(ref utf8JsonReaderUserScrubGeoSchema, jsonSerializerOptions, out userScrubGeoSchema);

                    Utf8JsonReader utf8JsonReaderUserProfileModificationComplianceSchema = utf8JsonReader;
                    ClientUtils.TryDeserialize<UserProfileModificationComplianceSchema?>(ref utf8JsonReaderUserProfileModificationComplianceSchema, jsonSerializerOptions, out userProfileModificationComplianceSchema);
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        default:
                            break;
                    }
                }
            }

            if (userProtectComplianceSchema != null)
                return new UserComplianceData(userProtectComplianceSchema);

            if (userUnprotectComplianceSchema != null)
                return new UserComplianceData(userUnprotectComplianceSchema);

            if (userDeleteComplianceSchema != null)
                return new UserComplianceData(userDeleteComplianceSchema);

            if (userUndeleteComplianceSchema != null)
                return new UserComplianceData(userUndeleteComplianceSchema);

            if (userSuspendComplianceSchema != null)
                return new UserComplianceData(userSuspendComplianceSchema);

            if (userUnsuspendComplianceSchema != null)
                return new UserComplianceData(userUnsuspendComplianceSchema);

            if (userWithheldComplianceSchema != null)
                return new UserComplianceData(userWithheldComplianceSchema);

            if (userScrubGeoSchema != null)
                return new UserComplianceData(userScrubGeoSchema);

            if (userProfileModificationComplianceSchema != null)
                return new UserComplianceData(userProfileModificationComplianceSchema);

            throw new JsonException();
        }

        /// <summary>
        /// Serializes a <see cref="UserComplianceData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userComplianceData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UserComplianceData userComplianceData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, userComplianceData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UserComplianceData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userComplianceData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UserComplianceData userComplianceData, JsonSerializerOptions jsonSerializerOptions)
        {

        }
    }
}
