// <auto-generated>
/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.128
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// UserTakedownComplianceSchema
    /// </summary>
    public partial class UserTakedownComplianceSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserTakedownComplianceSchema" /> class.
        /// </summary>
        /// <param name="eventAt">Event time.</param>
        /// <param name="user">user</param>
        /// <param name="withheldInCountries">withheldInCountries</param>
        [JsonConstructor]
        public UserTakedownComplianceSchema(DateTime eventAt, UserComplianceSchemaUser user, List<string> withheldInCountries)
        {
            EventAt = eventAt;
            User = user;
            WithheldInCountries = withheldInCountries;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Event time.
        /// </summary>
        /// <value>Event time.</value>
        /* <example>2021-07-06T18:40:40Z</example> */
        [JsonPropertyName("event_at")]
        public DateTime EventAt { get; set; }

        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [JsonPropertyName("user")]
        public UserComplianceSchemaUser User { get; set; }

        /// <summary>
        /// Gets or Sets WithheldInCountries
        /// </summary>
        [JsonPropertyName("withheld_in_countries")]
        public List<string> WithheldInCountries { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserTakedownComplianceSchema {\n");
            sb.Append("  EventAt: ").Append(EventAt).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  WithheldInCountries: ").Append(WithheldInCountries).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UserTakedownComplianceSchema" />
    /// </summary>
    public class UserTakedownComplianceSchemaJsonConverter : JsonConverter<UserTakedownComplianceSchema>
    {
        /// <summary>
        /// The format to use to serialize EventAt
        /// </summary>
        public static string EventAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="UserTakedownComplianceSchema" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UserTakedownComplianceSchema Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DateTime?> eventAt = default;
            Option<UserComplianceSchemaUser?> user = default;
            Option<List<string>?> withheldInCountries = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "event_at":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                eventAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "user":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                user = new Option<UserComplianceSchemaUser?>(JsonSerializer.Deserialize<UserComplianceSchemaUser>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "withheld_in_countries":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                withheldInCountries = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!eventAt.IsSet)
                throw new ArgumentException("Property is required for class UserTakedownComplianceSchema.", nameof(eventAt));

            if (!user.IsSet)
                throw new ArgumentException("Property is required for class UserTakedownComplianceSchema.", nameof(user));

            if (!withheldInCountries.IsSet)
                throw new ArgumentException("Property is required for class UserTakedownComplianceSchema.", nameof(withheldInCountries));

            if (eventAt.IsSet && eventAt.Value == null)
                throw new ArgumentNullException(nameof(eventAt), "Property is not nullable for class UserTakedownComplianceSchema.");

            if (user.IsSet && user.Value == null)
                throw new ArgumentNullException(nameof(user), "Property is not nullable for class UserTakedownComplianceSchema.");

            if (withheldInCountries.IsSet && withheldInCountries.Value == null)
                throw new ArgumentNullException(nameof(withheldInCountries), "Property is not nullable for class UserTakedownComplianceSchema.");

            return new UserTakedownComplianceSchema(eventAt.Value!.Value!, user.Value!, withheldInCountries.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="UserTakedownComplianceSchema" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userTakedownComplianceSchema"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UserTakedownComplianceSchema userTakedownComplianceSchema, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, userTakedownComplianceSchema, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UserTakedownComplianceSchema" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userTakedownComplianceSchema"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UserTakedownComplianceSchema userTakedownComplianceSchema, JsonSerializerOptions jsonSerializerOptions)
        {
            if (userTakedownComplianceSchema.User == null)
                throw new ArgumentNullException(nameof(userTakedownComplianceSchema.User), "Property is required for class UserTakedownComplianceSchema.");

            if (userTakedownComplianceSchema.WithheldInCountries == null)
                throw new ArgumentNullException(nameof(userTakedownComplianceSchema.WithheldInCountries), "Property is required for class UserTakedownComplianceSchema.");

            writer.WriteString("event_at", userTakedownComplianceSchema.EventAt.ToString(EventAtFormat));

            writer.WritePropertyName("user");
            JsonSerializer.Serialize(writer, userTakedownComplianceSchema.User, jsonSerializerOptions);
            writer.WritePropertyName("withheld_in_countries");
            JsonSerializer.Serialize(writer, userTakedownComplianceSchema.WithheldInCountries, jsonSerializerOptions);
        }
    }
}
