// <auto-generated>
/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.128
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// UserProfileModificationComplianceSchema
    /// </summary>
    public partial class UserProfileModificationComplianceSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserProfileModificationComplianceSchema" /> class.
        /// </summary>
        /// <param name="userProfileModification">userProfileModification</param>
        [JsonConstructor]
        public UserProfileModificationComplianceSchema(UserProfileModificationObjectSchema userProfileModification)
        {
            UserProfileModification = userProfileModification;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets UserProfileModification
        /// </summary>
        [JsonPropertyName("user_profile_modification")]
        public UserProfileModificationObjectSchema UserProfileModification { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserProfileModificationComplianceSchema {\n");
            sb.Append("  UserProfileModification: ").Append(UserProfileModification).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UserProfileModificationComplianceSchema" />
    /// </summary>
    public class UserProfileModificationComplianceSchemaJsonConverter : JsonConverter<UserProfileModificationComplianceSchema>
    {
        /// <summary>
        /// Deserializes json to <see cref="UserProfileModificationComplianceSchema" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UserProfileModificationComplianceSchema Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<UserProfileModificationObjectSchema?> userProfileModification = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "user_profile_modification":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                userProfileModification = new Option<UserProfileModificationObjectSchema?>(JsonSerializer.Deserialize<UserProfileModificationObjectSchema>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!userProfileModification.IsSet)
                throw new ArgumentException("Property is required for class UserProfileModificationComplianceSchema.", nameof(userProfileModification));

            if (userProfileModification.IsSet && userProfileModification.Value == null)
                throw new ArgumentNullException(nameof(userProfileModification), "Property is not nullable for class UserProfileModificationComplianceSchema.");

            return new UserProfileModificationComplianceSchema(userProfileModification.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="UserProfileModificationComplianceSchema" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userProfileModificationComplianceSchema"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UserProfileModificationComplianceSchema userProfileModificationComplianceSchema, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, userProfileModificationComplianceSchema, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UserProfileModificationComplianceSchema" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userProfileModificationComplianceSchema"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UserProfileModificationComplianceSchema userProfileModificationComplianceSchema, JsonSerializerOptions jsonSerializerOptions)
        {
            if (userProfileModificationComplianceSchema.UserProfileModification == null)
                throw new ArgumentNullException(nameof(userProfileModificationComplianceSchema.UserProfileModification), "Property is required for class UserProfileModificationComplianceSchema.");

            writer.WritePropertyName("user_profile_modification");
            JsonSerializer.Serialize(writer, userProfileModificationComplianceSchema.UserProfileModification, jsonSerializerOptions);
        }
    }
}
