// <auto-generated>
/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.128
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// UserWithheldComplianceSchema
    /// </summary>
    public partial class UserWithheldComplianceSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserWithheldComplianceSchema" /> class.
        /// </summary>
        /// <param name="userWithheld">userWithheld</param>
        [JsonConstructor]
        public UserWithheldComplianceSchema(UserTakedownComplianceSchema userWithheld)
        {
            UserWithheld = userWithheld;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets UserWithheld
        /// </summary>
        [JsonPropertyName("user_withheld")]
        public UserTakedownComplianceSchema UserWithheld { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserWithheldComplianceSchema {\n");
            sb.Append("  UserWithheld: ").Append(UserWithheld).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UserWithheldComplianceSchema" />
    /// </summary>
    public class UserWithheldComplianceSchemaJsonConverter : JsonConverter<UserWithheldComplianceSchema>
    {
        /// <summary>
        /// Deserializes json to <see cref="UserWithheldComplianceSchema" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UserWithheldComplianceSchema Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<UserTakedownComplianceSchema?> userWithheld = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "user_withheld":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                userWithheld = new Option<UserTakedownComplianceSchema?>(JsonSerializer.Deserialize<UserTakedownComplianceSchema>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!userWithheld.IsSet)
                throw new ArgumentException("Property is required for class UserWithheldComplianceSchema.", nameof(userWithheld));

            if (userWithheld.IsSet && userWithheld.Value == null)
                throw new ArgumentNullException(nameof(userWithheld), "Property is not nullable for class UserWithheldComplianceSchema.");

            return new UserWithheldComplianceSchema(userWithheld.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="UserWithheldComplianceSchema" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userWithheldComplianceSchema"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UserWithheldComplianceSchema userWithheldComplianceSchema, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, userWithheldComplianceSchema, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UserWithheldComplianceSchema" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userWithheldComplianceSchema"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UserWithheldComplianceSchema userWithheldComplianceSchema, JsonSerializerOptions jsonSerializerOptions)
        {
            if (userWithheldComplianceSchema.UserWithheld == null)
                throw new ArgumentNullException(nameof(userWithheldComplianceSchema.UserWithheld), "Property is required for class UserWithheldComplianceSchema.");

            writer.WritePropertyName("user_withheld");
            JsonSerializer.Serialize(writer, userWithheldComplianceSchema.UserWithheld, jsonSerializerOptions);
        }
    }
}
